#pragma once
#include <span>
#include "aura/body/Joint3D.hpp"
#include "aura/body/BodyPart3D.hpp"

namespace aura::body {
    struct ComponentVelocityAudit {
        math::Vec3 direction{};
        float modeSpeedBefore = 0.0f;
        float modeSpeedAfter = 0.0f;
        double predictedWork = 0.0;
        double linearWork = 0.0;
        double angularWork = 0.0;
        double quadraticEnergy = 0.0;
    };

    // World-space anchor velocity of translation plus the scalar rotation mode
    // generated by an impulse along worldDirection. No full inertia tensor.
    math::Vec3 componentAnchorVelocity(std::span<BodyPart3D *const> component,
                                      const math::Vec3 &worldAnchor,
                                      const math::Vec3 &worldDirection);

    // Experimental velocity-only projection. Parent responds as one body; the
    // disjoint child component receives a mass/inertia-accounted common motion.
    // Direction is seeded from actual anchor relative velocity, then held fixed.
    // No angle limits, geometry, contacts, integration, or runtime policy.
    ComponentVelocityAudit correctJointComponentModeVelocity(
        BodyPart3D &parent, BodyPart3D &child, const Joint3D &joint,
        std::span<BodyPart3D *const> childComponent);
}
